# Generated by Django 2.2.12 on 2020-11-03 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_fabricmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='shop.FabricModel'),
        ),
        migrations.AlterField(
            model_name='fabricmodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
    ]
