# Generated by Django 2.2.2 on 2020-11-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt_designer', '0003_auto_20201111_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collartype',
            name='type',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
