# Generated by Django 2.2.2 on 2020-11-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirt_designer', '0004_auto_20201111_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collar',
            name='fabric',
        ),
    ]
