# Generated by Django 2.2.2 on 2020-11-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_orderproduct'),
        ('shirt_designer', '0005_remove_collar_fabric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collar',
            name='type',
        ),
        migrations.AddField(
            model_name='collar',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.FabricModel'),
        ),
    ]
